"""events

Revision ID: 40f0ebcec7ce
Revises: 7924039747c1
Create Date: 2025-12-25 22:38:22.689145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40f0ebcec7ce"
down_revision: Union[str, Sequence[str], None] = "7924039747c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True)
    )
    op.add_column(
        "tg_users", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_users", "updated_at")
    op.drop_column("tg_users", "created_at")
    # ### end Alembic commands ###
