"""user relation

Revision ID: 13e7c7c52f38
Revises: d7da916f3250
Create Date: 2025-12-31 00:41:12.767264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e7c7c52f38'
down_revision: Union[str, Sequence[str], None] = 'd7da916f3250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'related_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relations')
    # ### end Alembic commands ###
