"""Add user table

Revision ID: 7924039747c1
Revises:
Create Date: 2025-12-25 21:07:10.080056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7924039747c1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("time_zone", sa.String(length=50), nullable=True),
        sa.Column("language_code", sa.String(length=5), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tg_users_id"), "tg_users", ["id"], unique=False)
    op.create_index(op.f("ix_tg_users_tg_id"), "tg_users", ["tg_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tg_users_tg_id"), table_name="tg_users")
    op.drop_index(op.f("ix_tg_users_id"), table_name="tg_users")
    op.drop_table("tg_users")
    # ### end Alembic commands ###
