"""timezone

Revision ID: e32bd3dd1d45
Revises: 3b8b7a30f212
Create Date: 2026-01-07 23:24:17.732649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32bd3dd1d45'
down_revision: Union[str, Sequence[str], None] = '3b8b7a30f212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('time_zone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'time_zone')
    # ### end Alembic commands ###
