"""user tz

Revision ID: d06c961d501b
Revises: e029bdacceb8
Create Date: 2026-01-05 12:39:42.462541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06c961d501b'
down_revision: Union[str, Sequence[str], None] = 'e029bdacceb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('time_shift', sa.Integer(), nullable=True))
    op.add_column('tg_users', sa.Column('is_chat', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Признак пользователя или чата'))
    op.drop_column('tg_users', 'time_zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('time_zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('tg_users', 'is_chat')
    op.drop_column('tg_users', 'time_shift')
    # ### end Alembic commands ###
