"""big int for event

Revision ID: 3b8b7a30f212
Revises: 87425c7b59df
Create Date: 2026-01-07 22:30:52.314262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8b7a30f212'
down_revision: Union[str, Sequence[str], None] = '87425c7b59df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Юзер тг id, кому принадлежит событие',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Юзер тг id, кому принадлежит событие',
               existing_nullable=False)
    # ### end Alembic commands ###
