"""init

Revision ID: aee9c4d4e797
Revises:
Create Date: 2026-01-04 00:00:40.683136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee9c4d4e797'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False, comment='Описание события'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Время начала события'),
    sa.Column('event_date_pickup', sa.Date(), nullable=False, comment='Выбранная дата на календаре'),
    sa.Column('single_event', sa.Boolean(), nullable=True, comment='Флаг если событие одиночное'),
    sa.Column('daily', sa.Boolean(), nullable=True, comment='Флаг, если событие ежедневное'),
    sa.Column('weekly', sa.Integer(), nullable=True, comment='Номер недели, если событие еженедельное'),
    sa.Column('monthly', sa.Integer(), nullable=True, comment='День, если событие ежемесячное'),
    sa.Column('annual_day', sa.Integer(), nullable=True, comment='День, если событие ежегодное'),
    sa.Column('annual_month', sa.Integer(), nullable=True, comment='Месяц, если событие ежегодное'),
    sa.Column('stop_time', sa.Time(), nullable=True, comment='Время окончания события'),
    sa.Column('tg_id', sa.Integer(), nullable=False, comment='Юзер тг id, кому принадлежит событие'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('tg_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True, comment='Признак, писал ли пользователь боту'),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_users_id'), 'tg_users', ['id'], unique=False)
    op.create_index(op.f('ix_tg_users_tg_id'), 'tg_users', ['tg_id'], unique=True)
    op.create_table('canceled_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cancel_date', sa.Date(), nullable=False, comment='Дата отмены события'),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canceled_events_id'), 'canceled_events', ['id'], unique=False)
    op.create_table('user_relations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'related_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relations')
    op.drop_index(op.f('ix_canceled_events_id'), table_name='canceled_events')
    op.drop_table('canceled_events')
    op.drop_index(op.f('ix_tg_users_tg_id'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_id'), table_name='tg_users')
    op.drop_table('tg_users')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
